### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np

In [10]:
vector1 = np.random.uniform(0, 1, size = 10)
print(vector1)
print("Розмір вектоора:", vector1.shape)

[0.93489311 0.13543275 0.82676555 0.02496071 0.39400643 0.53063147
 0.34280187 0.7222654  0.14741422 0.30541155]
Розмір вектоора: (10,)


In [11]:
vector2 = np.random.rand(10)
print(vector2)
print("Розмір вектоора:", vector2.shape)

[0.41517552 0.88547816 0.18012863 0.80432628 0.48672094 0.40276621
 0.91721776 0.86934468 0.3822629  0.77791031]
Розмір вектоора: (10,)


In [12]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
print(matrix)
print("Розмір матриці:", matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [13]:
vector = np.random.uniform(0, 1, size = 10)
print(vector)
result = np.round(vector+10, 2)
print(result)

[0.67208961 0.12260649 0.13862083 0.62231723 0.05752775 0.91077597
 0.63553252 0.30663452 0.50036503 0.11317014]
[10.67 10.12 10.14 10.62 10.06 10.91 10.64 10.31 10.5  10.11]


In [14]:
print(matrix)
matrix_x_2 = 2 * matrix
print(matrix_x_2)

[[11 14 17]
 [20 23 26]
 [29 32 35]]
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [15]:
vector_squared = np.square(vector)
print(vector_squared)

[0.45170444 0.01503235 0.01921573 0.38727874 0.00330944 0.82951287
 0.40390158 0.09402473 0.25036517 0.01280748]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [16]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [19]:
result_matrix = np.dot(B,A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


Розмірність результату множення `result_matrix` на вектор `C` буде дорівнювати 2

In [22]:
result_vector = np.dot(result_matrix, C)
print(result_vector)

[[0.5202]
 [0.2846]]


В результаті множення `result_matrix` на `D` ми отримаємо матрицю 2х2

In [23]:
result_matrix_x_D = np.dot(result_matrix, D)
print(result_matrix_x_D)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [24]:
result_matrix_t = result_matrix.T
print(result_matrix_t)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [29]:
vector_t = vector.T
print(vector_t)
print(vector_t.shape)

[0.67208961 0.12260649 0.13862083 0.62231723 0.05752775 0.91077597
 0.63553252 0.30663452 0.50036503 0.11317014]
(10,)


Схоже, що нічого не змінилося, тому що vector - це одномірний масив. Для того щоб транспонування змінило його форму треба спочатку перетворити його на двомірний вектор-стовпець, або вектор-строку. Наприклад:

In [31]:
vector_column = vector.reshape(-1, 1)
print(vector_column)
print(vector_column.shape)
t_vector_column = vector_column.T
print(t_vector_column)
print(t_vector_column.shape)

[[0.67208961]
 [0.12260649]
 [0.13862083]
 [0.62231723]
 [0.05752775]
 [0.91077597]
 [0.63553252]
 [0.30663452]
 [0.50036503]
 [0.11317014]]
(10, 1)
[[0.67208961 0.12260649 0.13862083 0.62231723 0.05752775 0.91077597
  0.63553252 0.30663452 0.50036503 0.11317014]]
(1, 10)


In [34]:
column_vector = np.expand_dims(vector, axis = 1)
print(column_vector)
print(column_vector.shape)

[[0.67208961]
 [0.12260649]
 [0.13862083]
 [0.62231723]
 [0.05752775]
 [0.91077597]
 [0.63553252]
 [0.30663452]
 [0.50036503]
 [0.11317014]]
(10, 1)


Операція `numpy.expand_dims` теж перетворює одновимірний масив на двовимірний.

In [35]:
column_vector_t = column_vector.T 
print(column_vector_t)
print(column_vector_t.shape)

[[0.67208961 0.12260649 0.13862083 0.62231723 0.05752775 0.91077597
  0.63553252 0.30663452 0.50036503 0.11317014]]
(1, 10)
